export const DEFAULT_BUSINESSES = [
  {
    id: 'rsa',
    name: 'Reliable Solutions Atlanta',
    slug: 'rsa',
    website: 'waterhelpme.com',
    industry: 'home_service',
    industry_label: 'Foundation Repair & Waterproofing',
    tagline: '',
    primary_color: '#1B4D7A',
    secondary_color: '#2E86C1',
    accent_color: '#E67E22',
    bg_color: '#0D2137',
    text_color: '#FFFFFF',
    tone: 'Authoritative and trustworthy. Speak like a seasoned expert who genuinely cares about protecting homes. Not salesy, not desperate. Calm confidence. The kind of contractor homeowners trust with their biggest investment.',
    icp: 'Homeowners in metro Atlanta experiencing water intrusion, foundation cracks, or crawl space issues. Age 35-65, value quality and warranties over lowest price. Often found the problem during a home inspection or noticed water in their basement.',
    services: 'Foundation Repair, Basement Waterproofing, Crawl Space Encapsulation, French Drains, Sump Pumps, Crack Injection',
    service_areas: 'Atlanta, Marietta, Decatur, Roswell, Alpharetta, Johns Creek, Kennesaw',
    certifications: '',
    cta_phrases: 'Schedule Your Free Inspection, Protect Your Home Today, Call For a Free Estimate',
    fact_sheet: '',
    banned_words: '',
  },
  {
    id: 'vac',
    name: 'VoiceAI Connect',
    slug: 'voiceai',
    website: 'myvoiceaiconnect.com',
    industry: 'saas_tech',
    industry_label: 'AI SaaS / White-Label AI Receptionist',
    tagline: '',
    primary_color: '#6C3CE1',
    secondary_color: '#8B5CF6',
    accent_color: '#10B981',
    bg_color: '#0A0A1A',
    text_color: '#FFFFFF',
    tone: 'Confident, modern, tech-forward. Speak to agency owners who want leverage and scale, not hype. No fluff, no buzzwords. Results-oriented language. Think founder-to-founder, not brand-to-consumer.',
    icp: 'Marketing agency owners running local lead gen or home service agencies. They want a recurring revenue product to offer clients. Revenue-focused, not hobbyists. Already running ads, already have clients, want to add MRR.',
    services: 'White-Label AI Receptionist Platform, Agency Dashboard, Client Management, VAPI Integration, Stripe Connect Billing',
    service_areas: 'United States, Canada, International',
    certifications: '',
    cta_phrases: 'Start Your Free Trial, See It In Action, Book a Demo',
    fact_sheet: '',
    banned_words: '',
  },
  {
    id: 'cb',
    name: 'CallBird AI',
    slug: 'callbird',
    website: 'callbirdai.com',
    industry: 'saas_smb',
    industry_label: 'AI Receptionist SaaS',
    tagline: '',
    primary_color: '#122092',
    secondary_color: '#1E3AC9',
    accent_color: '#F6B828',
    bg_color: '#0A0E2A',
    text_color: '#FFFFFF',
    tone: 'Friendly, reliable, professional. The AI receptionist that never misses a call. Approachable but competent. Speak to busy business owners who are tired of missing revenue.',
    icp: 'Small business owners (plumbers, dentists, lawyers, salons) who miss calls and lose revenue. Want simple setup, not technical complexity. Often a one-person or small team operation.',
    services: 'AI Phone Receptionist, Call Routing, Appointment Booking, After-Hours Answering, SMS Follow-Up',
    service_areas: 'United States',
    certifications: '',
    cta_phrases: 'Never Miss Another Call, Try Free For 14 Days, See How It Works',
    fact_sheet: '',
    banned_words: '',
  },
  {
    id: 'rs',
    name: 'Rocket Solutions',
    slug: 'rocket',
    website: 'rocketsolutions.io',
    industry: 'agency_dev',
    industry_label: 'Web Development & Consulting',
    tagline: '',
    primary_color: '#DC2626',
    secondary_color: '#991B1B',
    accent_color: '#FBBF24',
    bg_color: '#1A0A0A',
    text_color: '#FFFFFF',
    tone: 'Bold, direct, results-oriented. We build what you need, fast. No corporate speak. Speak like a developer who also understands business.',
    icp: 'Small to mid-size businesses needing websites, web apps, or digital consulting. Value speed and competence over fancy proposals.',
    services: 'Web Development, Web Applications, SEO, Digital Strategy, Consulting',
    service_areas: 'Atlanta, Nationwide',
    certifications: '',
    cta_phrases: "Let's Build Something, Get Started Today, Schedule a Call",
    fact_sheet: '',
    banned_words: '',
  },
  {
    id: 'gtc',
    name: 'GTC Group',
    slug: 'gtc',
    website: 'gtcgroup.io',
    industry: 'consulting',
    industry_label: 'Business Consulting & Services',
    tagline: '',
    primary_color: '#0F766E',
    secondary_color: '#14B8A6',
    accent_color: '#F59E0B',
    bg_color: '#0A1A18',
    text_color: '#FFFFFF',
    tone: 'Professional, strategic, consultative. We help businesses grow systematically. Speak with authority on operations, systems, and growth.',
    icp: 'Business owners looking for operational improvements, growth strategy, and technology integration. Typically doing $500K-5M revenue, hitting a ceiling.',
    services: 'Business Consulting, Growth Strategy, Technology Integration, Process Optimization',
    service_areas: 'Atlanta, Southeast US',
    certifications: '',
    cta_phrases: 'Scale Your Business, Book a Strategy Session, Learn More',
    fact_sheet: '',
    banned_words: '',
  },
];
