export const DEFAULT_BUSINESSES = [
  {
    id: 'rsa',
    name: 'Reliable Solutions Atlanta',
    slug: 'rsa',
    website: 'waterhelpme.com',
    industry: 'home_service',
    industry_label: 'Foundation Repair & Waterproofing',
    tagline: '',
    primary_color: '#273373',
    secondary_color: '#2692CC',
    accent_color: '#84D2F2',
    bg_color: '#0C1224',
    text_color: '#FFFFFF',
    tone: 'Authoritative and trustworthy. Speak like a seasoned expert who genuinely cares about protecting homes. Not salesy, not desperate. Calm confidence. The kind of contractor homeowners trust with their biggest investment. Reference Atlanta-specific things like red clay soil, heavy spring rain, older homes in Decatur and Marietta.',
    icp: 'Homeowners in metro Atlanta experiencing water intrusion, foundation cracks, or crawl space issues. Age 35-65, value quality and warranties over lowest price. Often found the problem during a home inspection or noticed water in their basement after heavy rain.',
    services: 'Foundation Repair, Basement Waterproofing, Crawl Space Encapsulation, French Drains, Sump Pumps, Crack Injection',
    service_areas: 'Atlanta, Marietta, Decatur, Roswell, Alpharetta, Johns Creek, Kennesaw',
    certifications: '',
    cta_phrases: 'Schedule Your Free Inspection, Protect Your Home Today, Call For a Free Estimate',
    fact_sheet: '',
    banned_words: '',
  },
  {
    id: 'vac',
    name: 'VoiceAI Connect',
    slug: 'voiceai',
    website: 'myvoiceaiconnect.com',
    industry: 'saas_tech',
    industry_label: 'AI SaaS / White-Label AI Receptionist',
    tagline: '',
    primary_color: '#FFFFFF',
    secondary_color: '#A0A0A0',
    accent_color: '#FFFFFF',
    bg_color: '#0A0A0A',
    text_color: '#FFFFFF',
    tone: 'Confident, modern, tech-forward. Speak to agency owners who want leverage and scale, not hype. No fluff, no buzzwords. Results-oriented language. Think founder-to-founder, not brand-to-consumer. The brand is monochrome and premium — black and white, no color.',
    icp: 'Marketing agency owners running local lead gen or home service agencies. They want a recurring revenue product to offer clients. Revenue-focused, not hobbyists. Already running ads, already have clients, want to add MRR.',
    services: 'White-Label AI Receptionist Platform, Agency Dashboard, Client Management, VAPI Integration, Stripe Connect Billing, Custom Domain Support, Multi-Tenant Architecture',
    service_areas: 'United States, Canada, International',
    certifications: '',
    cta_phrases: 'Start Your Free Trial, See It In Action, Book a Demo',
    fact_sheet: '',
    banned_words: 'revolutionary, cutting-edge, game-changer, disrupt',
  },
  {
    id: 'cb',
    name: 'CallBird AI',
    slug: 'callbird',
    website: 'callbirdai.com',
    industry: 'saas_smb',
    industry_label: 'AI Receptionist SaaS',
    tagline: '',
    primary_color: '#122092',
    secondary_color: '#1E3ABF',
    accent_color: '#F6B828',
    bg_color: '#0A0E2A',
    text_color: '#FFFFFF',
    tone: 'Friendly, reliable, professional. The AI receptionist that never misses a call. Approachable but competent. Speak to busy business owners who are tired of missing revenue. The blue jay mascot gives the brand personality — confident, sharp, always alert.',
    icp: 'Small business owners (plumbers, dentists, lawyers, salons) who miss calls and lose revenue. Want simple setup, not technical complexity. Often a one-person or small team operation.',
    services: 'AI Phone Receptionist, Call Routing, Appointment Booking, After-Hours Answering, SMS Follow-Up',
    service_areas: 'United States',
    certifications: '',
    cta_phrases: 'Never Miss Another Call, Try Free For 14 Days, See How It Works',
    fact_sheet: '',
    banned_words: '',
  },
  {
    id: 'rs',
    name: 'Rocket Solutions',
    slug: 'rocket',
    website: 'gorocketsolutions.com',
    industry: 'agency_dev',
    industry_label: 'Web Development & Consulting',
    tagline: '',
    primary_color: '#FA8820',
    secondary_color: '#E06D10',
    accent_color: '#FBBF24',
    bg_color: '#1A0E04',
    text_color: '#FFFFFF',
    tone: 'Bold, direct, results-oriented. We build what you need, fast. No corporate speak. Speak like a developer who also understands business. Orange energy — fast, modern, no wasted time.',
    icp: 'Small to mid-size businesses needing websites, web apps, or digital consulting. Value speed and competence over fancy proposals.',
    services: 'Web Development, Web Applications, SEO, Digital Strategy, Consulting',
    service_areas: 'Atlanta, Nationwide',
    certifications: '',
    cta_phrases: "Let's Build Something, Get Started Today, Schedule a Call",
    fact_sheet: '',
    banned_words: '',
  },
  {
    id: 'gtc',
    name: 'The GTC Group',
    slug: 'gtc',
    website: 'globaltransportconsultinggroup.com',
    industry: 'logistics_advisory',
    industry_label: 'Logistics Advisory for Independent Carriers',
    tagline: 'Carrier Resources, Brokerage Results',
    primary_color: '#C9A227',
    secondary_color: '#1A2744',
    accent_color: '#D4B44A',
    bg_color: '#0A0F1C',
    text_color: '#FFFFFF',
    tone: 'Authoritative, experienced, no-nonsense. Speak like former brokerage professionals who understand the carrier side. Premium and confident. Gold-on-black brand. Talk money, savings, and competitive advantage. Never generic business advice — always logistics-specific.',
    icp: 'Independent trucking carriers and small-to-mid-size fleet owners (1-50 trucks) who are overpaying for insurance, fuel, and maintenance. They know they are at a disadvantage against mega-carriers but do not know how to fix it. Revenue $500K-$10M.',
    services: 'Insurance Procurement & Optimization, Bulk Fuel Purchasing, Maintenance Network Access, Driver Services & Recruitment, Dedicated Sales Representation, Lane Acquisition & Optimization, Direct Shipper Connections, Rate Renegotiation, Professional Website & Marketing, Brand Identity Development',
    service_areas: 'Nationwide (United States)',
    certifications: '',
    cta_phrases: 'Book a Discovery Call, Claim Your Free Assessment, See How We Help',
    fact_sheet: 'Founded by former brokerage professionals. Team has collectively managed over $500 million in freight. $3-8K average savings per truck per year. 35+ carriers in network. 1-week ROI guarantee or money back. 15-25% revenue increase typical from cutting out load board middlemen. Contact: J. Brewer, jbrewer@gtcadvisers.com, (770) 533-2544.',
    banned_words: '',
  },
];